server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG


spring:
  messages:
    basename: messages # 사용할 다국어 파일의 이름을 messages로 하겠다.
    #=====
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #==Failed to start bean 'documentationPluginsBootstrapper' 에러 때문에 추가. Swagger관련. 해결못함.
